import os
import requests
import json
from groq import Groq

# Get inputs from environment
GROQ_API_KEY = os.environ.get("INPUT_GROQ-API-KEY")
GITHUB_TOKEN = os.environ.get("INPUT_GITHUB-TOKEN")
GITHUB_REPOSITORY = os.environ.get("GITHUB_REPOSITORY")
PR_NUMBER = os.environ.get("PR_NUMBER")

client = Groq(api_key=GROQ_API_KEY)

def get_pr_files():
    """Get all files changed in the PR"""
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/pulls/{PR_NUMBER}/files"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    response = requests.get(url, headers=headers)
    return response.json()

def analyze_code(filename, code):
    """Send code to Groq AI for security analysis"""
    prompt = f"""You are an elite application security engineer. Analyze this code for OWASP Top 10 vulnerabilities.

Filename: {filename}
Code:
{code}

Check for:
1. SQL Injection
2. Cross-Site Scripting (XSS)
3. Hardcoded secrets or API keys
4. Insecure dependencies
5. Broken authentication
6. Sensitive data exposure
7. Security misconfigurations
8. Insecure deserialization
9. Command injection
10. Path traversal

Respond in this EXACT format:

RISK_LEVEL: [CRITICAL|HIGH|MEDIUM|LOW|CLEAN]

FINDINGS:
List each vulnerability found with line references. If none, write: No vulnerabilities detected.

RECOMMENDATIONS:
List specific fixes for each finding. If none, write: Code appears secure.
"""
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=1000,
    )
    return response.choices[0].message.content

def post_comment(comment):
    """Post analysis result as PR comment"""
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/issues/{PR_NUMBER}/comments"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    data = {"body": comment}
    requests.post(url, headers=headers, json=data)

def build_comment(results):
    """Build a beautiful markdown comment"""
    comment = "## 🛡️ AI Security Scanner — OWASP Analysis Report\n\n"
    comment += "> Powered by Groq AI — Automated security review for this PR\n\n"
    comment += "---\n\n"

    has_issues = False

    for filename, analysis in results.items():
        risk = "UNKNOWN"
        if "RISK_LEVEL: CRITICAL" in analysis: risk = "🔴 CRITICAL"
        elif "RISK_LEVEL: HIGH" in analysis: risk = "🟠 HIGH"
        elif "RISK_LEVEL: MEDIUM" in analysis: risk = "🟡 MEDIUM"
        elif "RISK_LEVEL: LOW" in analysis: risk = "🟢 LOW"
        elif "RISK_LEVEL: CLEAN" in analysis: risk = "✅ CLEAN"

        if risk not in ["✅ CLEAN", "🟢 LOW"]:
            has_issues = True

        comment += f"### 📄 `{filename}`\n"
        comment += f"**Risk Level:** {risk}\n\n"
        comment += f"```\n{analysis}\n```\n\n"
        comment += "---\n\n"

    if has_issues:
        comment += "⚠️ **Action Required:** Security vulnerabilities were detected. Please review and fix before merging.\n"
    else:
        comment += "✅ **All Clear:** No significant security issues detected in this PR.\n"

    comment += "\n*Generated by [ai-security-scanner](https://github.com/tahahahaa/ai-security-scanner)*"
    return comment

def main():
    print("🛡️ AI Security Scanner starting...")
    files = get_pr_files()
    results = {}

    for f in files:
        filename = f.get("filename", "")
        patch = f.get("patch", "")

        # Only scan code files
        ext = filename.split(".")[-1].lower()
        if ext not in ["py","js","ts","php","java","go","rb","cs","cpp","c","html","env"]:
            print(f"Skipping {filename} — not a code file")
            continue

        if not patch:
            print(f"Skipping {filename} — no changes detected")
            continue

        print(f"Scanning {filename}...")
        analysis = analyze_code(filename, patch)
        results[filename] = analysis
        print(f"Done: {filename}")

    if results:
        comment = build_comment(results)
        post_comment(comment)
        print("✅ Analysis posted as PR comment!")
    else:
        print("No scannable files found in this PR.")

if __name__ == "__main__":
    main()